import { Montserrat } from 'next/font/google';
import "./globals.css";
import RouteLoader from './components/Spinner';
// font Montserrat
const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-montserrat'
});

export const metadata = {
  title: "evisa.welcometoserbia.gov.rs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}>
        <RouteLoader>{children}</RouteLoader>
      </body>
    </html>
  );
}
